#!/bin/sh
set -ex
#
# Note: Debug option 1 (-D 1); first map only (-M 1,1);
# use level variable as ensemble (-l ensemble_member);
# use first ensemble (-L 1);
# -p is path to udunits.dat
#
# The input j2.nc is in NetCDF3 format. This was output using cdo:
#
# Try run-nc2cmp SIM 2000 Mslp

alias read_nc2cmp='/g/data/w40/cb4350/temp2/cts.dir/software.dir/cyc.dir/cycbin/read_nc2cmp'

if [[ $# -ne 4 ]]; then
  echo "Usage: run-nc2cmp model year (4-digits) level"
  echo "e.g.,  run-nc2cmp SIM 0.5-4-12 92 Mslp"
  exit
else
  d=$1
  s=$2
  yr=$3
  lev=$4
fi

dNC=/g/data/w40/cb4350/temp2/cts.dir/software.dir/cyc.dir/data/  #path to input data
:

echo ${dNC}
echo $lev
if [[ "$lev" == "Mslp" ]];then
fNC=${dNC}${s}/daily
else
echo "wrong branch... FIX"
fNC=${dNC}${s}/daily
fi
:
echo $fNC
fEXT=.nc
if [ -e ${fNC}${fEXT} ]; then
echo ${fNC}${fEXT}
:
echo $lev
  if [[ $lev == "Mslp" ]]; then
    echo "CLB - First Branch"
    mkdir -p cmp_$d
    fCMP=cmp_$d/$d.$lev.${yr}.cmp
    read_nc2cmp -i ${fNC}${fEXT} -o $fCMP -d "lon,lat,time" \
    -u slp -v PMSL -U hPa -s 1.0 -r $d -p ../udunits/bin/udunits.dat
   # -u ps -v PMSL -U pascals -s 0.01 -r $d -p ../udunits/bin/udunits.dat  
  elif [[ $lev -eq "Mslp" ]]; then
    echo "CLB - Second Branch" 
    mkdir -p cmp_$d
    fCMP=cmp_$d/$d.$lev.${yr}.cmp
    read_nc2cmp -I -i ${fNC}${fEXT} -o $fCMP -d "lon,lat,time" \
    -u ps -s 0.01 -U pascals -v Z$lev -r $d -g "2.8125x2.7893DEG" -p /g/data/w40/cb4350/temp/source/cycbin/udunits.dat    
    # make sure that the dimensions are equal to the one in the netcdf file
    # adapt variable name (var1), factor behind -s must be adapted if already in hPa 
  fi
fi
:
exit
